services:
  app:
    build:
      context: .
      dockerfile: infrastructure/backend/Dockerfile
    ports:
      - "${APP_PORT}:3000"
  nginx-proxy:
    build:
        context: .
        dockerfile: infrastructure/frontend/Dockerfile
    ports:
      - "${NGINX_PORT}:8080"
    depends_on:
      - app
